/*
 * generated by Xtext 2.34.0
 */
package compilador.parser.antlr;

import com.google.inject.Inject;
import compilador.parser.antlr.internal.InternalSolemParser;
import compilador.services.SolemGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SolemParser extends AbstractAntlrParser {

	@Inject
	private SolemGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSolemParser createParser(XtextTokenStream stream) {
		return new InternalSolemParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Programa";
	}

	public SolemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SolemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
