/*
 * generated by Xtext 2.34.0
 */
package compilador.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SolemUiModule extends AbstractSolemUiModule {

	public SolemUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
