/*
 * generated by Xtext 2.34.0
 */
package compilador.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSolemScopeProvider extends DelegatingScopeProvider {
}
