/*
 * generated by Xtext 2.34.0
 */
package compilador;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SolemRuntimeModule extends AbstractSolemRuntimeModule {
}
