/**
 * generated by Xtext 2.34.0
 */
package compilador.solem.impl;

import compilador.solem.FatorAritmetico;
import compilador.solem.SolemPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FatorAritmeticoImpl extends MinimalEObjectImpl.Container implements FatorAritmetico
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FatorAritmeticoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SolemPackage.Literals.FATOR_ARITMETICO;
  }

} //FatorAritmeticoImpl
