/**
 * generated by Xtext 2.34.0
 */
package compilador.solem.impl;

import compilador.solem.SolemPackage;
import compilador.solem.TermoRelacional;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Termo Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TermoRelacionalImpl extends MinimalEObjectImpl.Container implements TermoRelacional
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TermoRelacionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SolemPackage.Literals.TERMO_RELACIONAL;
  }

} //TermoRelacionalImpl
