/*
 * generated by Xtext 2.34.0
 */
package compilador.ui;

import com.google.inject.Injector;
import compilador.solem.ui.internal.SolemActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SolemExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(SolemActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		SolemActivator activator = SolemActivator.getInstance();
		return activator != null ? activator.getInjector(SolemActivator.COMPILADOR_SOLEM) : null;
	}

}
