/*
 * generated by Xtext 2.34.0
 */
package compilador.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import compilador.SolemRuntimeModule;
import compilador.SolemStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SolemIdeSetup extends SolemStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SolemRuntimeModule(), new SolemIdeModule()));
	}
	
}
