/*
 * generated by Xtext 2.34.0
 */
package compilador.ui.tests;

import com.google.inject.Injector;
import compilador.solem.ui.internal.SolemActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SolemUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SolemActivator.getInstance().getInjector("compilador.Solem");
	}

}
