/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Condicao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.ComandoCondicao#getExp <em>Exp</em>}</li>
 *   <li>{@link compilador.solem.ComandoCondicao#getCmd1 <em>Cmd1</em>}</li>
 *   <li>{@link compilador.solem.ComandoCondicao#getCmd2 <em>Cmd2</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getComandoCondicao()
 * @model
 * @generated
 */
public interface ComandoCondicao extends Comando
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressaoRelacional)
   * @see compilador.solem.SolemPackage#getComandoCondicao_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressaoRelacional getExp();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoCondicao#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressaoRelacional value);

  /**
   * Returns the value of the '<em><b>Cmd1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd1</em>' containment reference.
   * @see #setCmd1(Comando)
   * @see compilador.solem.SolemPackage#getComandoCondicao_Cmd1()
   * @model containment="true"
   * @generated
   */
  Comando getCmd1();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoCondicao#getCmd1 <em>Cmd1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd1</em>' containment reference.
   * @see #getCmd1()
   * @generated
   */
  void setCmd1(Comando value);

  /**
   * Returns the value of the '<em><b>Cmd2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd2</em>' containment reference.
   * @see #setCmd2(Comando)
   * @see compilador.solem.SolemPackage#getComandoCondicao_Cmd2()
   * @model containment="true"
   * @generated
   */
  Comando getCmd2();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoCondicao#getCmd2 <em>Cmd2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd2</em>' containment reference.
   * @see #getCmd2()
   * @generated
   */
  void setCmd2(Comando value);

} // ComandoCondicao
