/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Entrada</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.ComandoEntrada#getVariavel <em>Variavel</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getComandoEntrada()
 * @model
 * @generated
 */
public interface ComandoEntrada extends Comando
{
  /**
   * Returns the value of the '<em><b>Variavel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variavel</em>' reference.
   * @see #setVariavel(Declaracao)
   * @see compilador.solem.SolemPackage#getComandoEntrada_Variavel()
   * @model
   * @generated
   */
  Declaracao getVariavel();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoEntrada#getVariavel <em>Variavel</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variavel</em>' reference.
   * @see #getVariavel()
   * @generated
   */
  void setVariavel(Declaracao value);

} // ComandoEntrada
