/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see compilador.solem.SolemPackage#getComando()
 * @model
 * @generated
 */
public interface Comando extends EObject
{
} // Comando
