/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comando Repeticao</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.ComandoRepeticao#getExp <em>Exp</em>}</li>
 *   <li>{@link compilador.solem.ComandoRepeticao#getCmd <em>Cmd</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getComandoRepeticao()
 * @model
 * @generated
 */
public interface ComandoRepeticao extends Comando
{
  /**
   * Returns the value of the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp</em>' containment reference.
   * @see #setExp(ExpressaoRelacional)
   * @see compilador.solem.SolemPackage#getComandoRepeticao_Exp()
   * @model containment="true"
   * @generated
   */
  ExpressaoRelacional getExp();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoRepeticao#getExp <em>Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp</em>' containment reference.
   * @see #getExp()
   * @generated
   */
  void setExp(ExpressaoRelacional value);

  /**
   * Returns the value of the '<em><b>Cmd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cmd</em>' containment reference.
   * @see #setCmd(Comando)
   * @see compilador.solem.SolemPackage#getComandoRepeticao_Cmd()
   * @model containment="true"
   * @generated
   */
  Comando getCmd();

  /**
   * Sets the value of the '{@link compilador.solem.ComandoRepeticao#getCmd <em>Cmd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cmd</em>' containment reference.
   * @see #getCmd()
   * @generated
   */
  void setCmd(Comando value);

} // ComandoRepeticao
