/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see compilador.solem.SolemPackage#getFatorAritmetico()
 * @model
 * @generated
 */
public interface FatorAritmetico extends EObject
{
} // FatorAritmetico
