/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outro Fator Aritmetico</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.OutroFatorAritmetico#getOperador <em>Operador</em>}</li>
 *   <li>{@link compilador.solem.OutroFatorAritmetico#getFator <em>Fator</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getOutroFatorAritmetico()
 * @model
 * @generated
 */
public interface OutroFatorAritmetico extends EObject
{
  /**
   * Returns the value of the '<em><b>Operador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operador</em>' attribute.
   * @see #setOperador(String)
   * @see compilador.solem.SolemPackage#getOutroFatorAritmetico_Operador()
   * @model
   * @generated
   */
  String getOperador();

  /**
   * Sets the value of the '{@link compilador.solem.OutroFatorAritmetico#getOperador <em>Operador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operador</em>' attribute.
   * @see #getOperador()
   * @generated
   */
  void setOperador(String value);

  /**
   * Returns the value of the '<em><b>Fator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fator</em>' containment reference.
   * @see #setFator(FatorAritmetico)
   * @see compilador.solem.SolemPackage#getOutroFatorAritmetico_Fator()
   * @model containment="true"
   * @generated
   */
  FatorAritmetico getFator();

  /**
   * Sets the value of the '{@link compilador.solem.OutroFatorAritmetico#getFator <em>Fator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fator</em>' containment reference.
   * @see #getFator()
   * @generated
   */
  void setFator(FatorAritmetico value);

} // OutroFatorAritmetico
