/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sub Algoritmo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.SubAlgoritmo#getComandos <em>Comandos</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getSubAlgoritmo()
 * @model
 * @generated
 */
public interface SubAlgoritmo extends Comando
{
  /**
   * Returns the value of the '<em><b>Comandos</b></em>' containment reference list.
   * The list contents are of type {@link compilador.solem.Comando}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comandos</em>' containment reference list.
   * @see compilador.solem.SolemPackage#getSubAlgoritmo_Comandos()
   * @model containment="true"
   * @generated
   */
  EList<Comando> getComandos();

} // SubAlgoritmo
