/**
 * generated by Xtext 2.34.0
 */
package compilador.solem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Termo Comparacao Relacional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link compilador.solem.TermoComparacaoRelacional#getExp1 <em>Exp1</em>}</li>
 *   <li>{@link compilador.solem.TermoComparacaoRelacional#getOpRel <em>Op Rel</em>}</li>
 *   <li>{@link compilador.solem.TermoComparacaoRelacional#getExp2 <em>Exp2</em>}</li>
 * </ul>
 *
 * @see compilador.solem.SolemPackage#getTermoComparacaoRelacional()
 * @model
 * @generated
 */
public interface TermoComparacaoRelacional extends TermoRelacional
{
  /**
   * Returns the value of the '<em><b>Exp1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp1</em>' containment reference.
   * @see #setExp1(ExpressaoAritmetica)
   * @see compilador.solem.SolemPackage#getTermoComparacaoRelacional_Exp1()
   * @model containment="true"
   * @generated
   */
  ExpressaoAritmetica getExp1();

  /**
   * Sets the value of the '{@link compilador.solem.TermoComparacaoRelacional#getExp1 <em>Exp1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp1</em>' containment reference.
   * @see #getExp1()
   * @generated
   */
  void setExp1(ExpressaoAritmetica value);

  /**
   * Returns the value of the '<em><b>Op Rel</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op Rel</em>' attribute.
   * @see #setOpRel(String)
   * @see compilador.solem.SolemPackage#getTermoComparacaoRelacional_OpRel()
   * @model
   * @generated
   */
  String getOpRel();

  /**
   * Sets the value of the '{@link compilador.solem.TermoComparacaoRelacional#getOpRel <em>Op Rel</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op Rel</em>' attribute.
   * @see #getOpRel()
   * @generated
   */
  void setOpRel(String value);

  /**
   * Returns the value of the '<em><b>Exp2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exp2</em>' containment reference.
   * @see #setExp2(ExpressaoAritmetica)
   * @see compilador.solem.SolemPackage#getTermoComparacaoRelacional_Exp2()
   * @model containment="true"
   * @generated
   */
  ExpressaoAritmetica getExp2();

  /**
   * Sets the value of the '{@link compilador.solem.TermoComparacaoRelacional#getExp2 <em>Exp2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exp2</em>' containment reference.
   * @see #getExp2()
   * @generated
   */
  void setExp2(ExpressaoAritmetica value);

} // TermoComparacaoRelacional
